export const LIST = [
  { phoneme: "æ", grapheme: "a", graphemeType: "Alphabet" },
  { phoneme: "b", grapheme: "b", graphemeType: "Alphabet" },
  { phoneme: "k", grapheme: "c", graphemeType: "Alphabet" },
  { phoneme: "d", grapheme: "d", graphemeType: "Alphabet" },
  { phoneme: "ɛ", grapheme: "e", graphemeType: "Alphabet" },
  { phoneme: "f", grapheme: "f", graphemeType: "Alphabet" },
  { phoneme: "ɡ", grapheme: "g", graphemeType: "Alphabet" },
  { phoneme: "h", grapheme: "h", graphemeType: "Alphabet" },
  { phoneme: "ɪ", grapheme: "i", graphemeType: "Alphabet" },
  { phoneme: "dʒ", grapheme: "j", graphemeType: "Alphabet" },
  { phoneme: "k", grapheme: "k", graphemeType: "Alphabet" },
  { phoneme: "ɫ", grapheme: "l", graphemeType: "Alphabet" },
  { phoneme: "m", grapheme: "m", graphemeType: "Alphabet" },
  { phoneme: "n", grapheme: "n", graphemeType: "Alphabet" },
  { phoneme: "ɑ", grapheme: "o", graphemeType: "Alphabet" },
  { phoneme: "p", grapheme: "p", graphemeType: "Alphabet" },
  { phoneme: "kw", grapheme: "q", graphemeType: "Alphabet" },
  { phoneme: "ɹ", grapheme: "r", graphemeType: "Alphabet" },
  { phoneme: "s", grapheme: "s", graphemeType: "Alphabet" },
  { phoneme: "t", grapheme: "t", graphemeType: "Alphabet" },
  { phoneme: "ə", grapheme: "u", graphemeType: "Alphabet" },
  { phoneme: "v", grapheme: "v", graphemeType: "Alphabet" },
  { phoneme: "w", grapheme: "w", graphemeType: "Alphabet" },
  { phoneme: "ks", grapheme: "x", graphemeType: "Alphabet" },
  { phoneme: "j", grapheme: "y", graphemeType: "Alphabet" },
  { phoneme: "z", grapheme: "z", graphemeType: "Alphabet" },
  { phoneme: "æd", grapheme: "ad", graphemeType: "ShortVowel+" },
  { phoneme: "æɡ", grapheme: "ag", graphemeType: "ShortVowel+" },
  { phoneme: "æt", grapheme: "at", graphemeType: "ShortVowel+" },
  { phoneme: "æm", grapheme: "am", graphemeType: "ShortVowel+" },
  { phoneme: "æn", grapheme: "an", graphemeType: "ShortVowel+" },
  { phoneme: "æp", grapheme: "ap", graphemeType: "ShortVowel+" },
  { phoneme: "ɛd", grapheme: "ed", graphemeType: "ShortVowel+" },
  { phoneme: "ɛɡ", grapheme: "eg", graphemeType: "ShortVowel+" },
  { phoneme: "ɛn", grapheme: "en", graphemeType: "ShortVowel+" },
  { phoneme: "ɛt", grapheme: "et", graphemeType: "ShortVowel+" },
  { phoneme: "ɛɫ", grapheme: "ell", graphemeType: "ShortVowel+" },
  { phoneme: "ɛs", grapheme: "ess", graphemeType: "ShortVowel+" },
  { phoneme: "ɪɡ", grapheme: "ig", graphemeType: "ShortVowel+" },
  { phoneme: "ɪn", grapheme: "in", graphemeType: "ShortVowel+" },
  { phoneme: "ɪb", grapheme: "ib", graphemeType: "ShortVowel+" },
  { phoneme: "ɪp", grapheme: "ip", graphemeType: "ShortVowel+" },
  { phoneme: "ɪd", grapheme: "id", graphemeType: "ShortVowel+" },
  { phoneme: "ɪt", grapheme: "it", graphemeType: "ShortVowel+" },
  { phoneme: "ɪks", grapheme: "ix", graphemeType: "ShortVowel+" },
  { phoneme: "ɪm", grapheme: "im", graphemeType: "ShortVowel+" },
  { phoneme: "ɪɫ", grapheme: "ill", graphemeType: "ShortVowel+" },
  { phoneme: "ɑp", grapheme: "op", graphemeType: "ShortVowel+" },
  { phoneme: "ɑt", grapheme: "ot", graphemeType: "ShortVowel+" },
  { phoneme: "ɑɡ", grapheme: "og", graphemeType: "ShortVowel+" },
  { phoneme: "ɑks", grapheme: "ox", graphemeType: "ShortVowel+" },
  { phoneme: "ɑd", grapheme: "od", graphemeType: "ShortVowel+" },
  { phoneme: "ɑb", grapheme: "ob", graphemeType: "ShortVowel+" },
  { phoneme: "əb", grapheme: "ub", graphemeType: "ShortVowel+" },
  { phoneme: "əp", grapheme: "up", graphemeType: "ShortVowel+" },
  { phoneme: "əd", grapheme: "ud", graphemeType: "ShortVowel+" },
  { phoneme: "əm", grapheme: "um", graphemeType: "ShortVowel+" },
  { phoneme: "ən", grapheme: "un", graphemeType: "ShortVowel+" },
  { phoneme: "əɫ", grapheme: "ull", graphemeType: "ShortVowel+" },
  { phoneme: "əɡ", grapheme: "ug", graphemeType: "ShortVowel+" },
  { phoneme: "ət", grapheme: "ut", graphemeType: "ShortVowel+" },
  { phoneme: "əs", grapheme: "us", graphemeType: "ShortVowel+" },
  { phoneme: "eɪ", grapheme: "a_e", graphemeType: "LongVowel+" },
  { phoneme: "aɪ", grapheme: "i_e", graphemeType: "LongVowel+" },
  { phoneme: "oʊ", grapheme: "o_e", graphemeType: "LongVowel+" },
  { phoneme: "ju", grapheme: "u_e", graphemeType: "LongVowel+" },
  {
    phoneme: "u",
    grapheme: "u_e",
    graphemeType: "LongVowel+",
    tips: "^(j|r|l|s)",
  },
  { phoneme: "i", grapheme: "e_e", graphemeType: "LongVowel+" },
  { phoneme: "eɪ", grapheme: "ai", graphemeType: "LongVowel+" },
  { phoneme: "eɪ", grapheme: "ay", graphemeType: "LongVowel+" },
  { phoneme: "i", grapheme: "ee", graphemeType: "LongVowel+" },
  { phoneme: "i", grapheme: "ea", graphemeType: "LongVowel+" },
  { phoneme: "i", grapheme: "ey", graphemeType: "LongVowel+" },
  { phoneme: "i", grapheme: "y", graphemeType: "LongVowel+", tips: "y$ ?" },
  { phoneme: "aɪ", grapheme: "ie", graphemeType: "LongVowel+" },
  { phoneme: "aɪ", grapheme: "igh", graphemeType: "LongVowel+" },
  {
    phoneme: "aɪ",
    grapheme: "y",
    graphemeType: "LongVowel+",
    tips: "y$ open?",
  },
  { phoneme: "oʊ", grapheme: "oa", graphemeType: "LongVowel+" },
  { phoneme: "oʊ", grapheme: "ow", graphemeType: "LongVowel+" },
  { phoneme: "ju", grapheme: "ew", graphemeType: "LongVowel+" },
  { phoneme: "ju", grapheme: "ue", graphemeType: "LongVowel+" },
  {
    phoneme: "u",
    grapheme: "ue",
    graphemeType: "LongVowel+",
    tips: "with s|l",
  },
  { phoneme: "u", grapheme: "ui", graphemeType: "LongVowel+" },
  { phoneme: "u", grapheme: "oo", graphemeType: "LongVowel+" },
  { phoneme: "bɫ", grapheme: "bl", graphemeType: "Consonant+" },
  { phoneme: "pɫ", grapheme: "pl", graphemeType: "Consonant+" },
  { phoneme: "kɫ", grapheme: "cl", graphemeType: "Consonant+" },
  { phoneme: "fɫ", grapheme: "fl", graphemeType: "Consonant+" },
  { phoneme: "ɡɫ", grapheme: "gl", graphemeType: "Consonant+" },
  { phoneme: "sɫ", grapheme: "sl", graphemeType: "Consonant+" },
  { phoneme: "pɹ", grapheme: "pr", graphemeType: "Consonant+" },
  { phoneme: "bɹ", grapheme: "br", graphemeType: "Consonant+" },
  { phoneme: "kɹ", grapheme: "cr", graphemeType: "Consonant+" },
  { phoneme: "ɡɹ", grapheme: "gr", graphemeType: "Consonant+" },
  { phoneme: "fɹ", grapheme: "fr", graphemeType: "Consonant+" },
  { phoneme: "tɹ", grapheme: "tr", graphemeType: "Consonant+" },
  { phoneme: "dɹ", grapheme: "dr", graphemeType: "Consonant+" },
  { phoneme: "sm", grapheme: "sm", graphemeType: "Consonant+" },
  { phoneme: "sn", grapheme: "sn", graphemeType: "Consonant+" },
  { phoneme: "sw", grapheme: "sw", graphemeType: "Consonant+" },
  { phoneme: "stɹ", grapheme: "str", graphemeType: "Consonant+" },
  { phoneme: "sp", grapheme: "sp", graphemeType: "Consonant+" },
  { phoneme: "st", grapheme: "st", graphemeType: "Consonant+" },
  { phoneme: "sk", grapheme: "sk", graphemeType: "Consonant+" },
  { phoneme: "sk", grapheme: "sc", graphemeType: "Consonant+" },
  { phoneme: "ʃ", grapheme: "sh", graphemeType: "Consonant+" },
  { phoneme: "f", grapheme: "ph", graphemeType: "Consonant+" },
  { phoneme: "θ", grapheme: "th", graphemeType: "Consonant+", tips: "three" },
  { phoneme: "ð", grapheme: "th", graphemeType: "Consonant+", tips: "this" },
  { phoneme: "w", grapheme: "wh", graphemeType: "Consonant+" },
  { phoneme: "tʃ", grapheme: "ch", graphemeType: "Consonant+" },
  { phoneme: "tʃ", grapheme: "tch", graphemeType: "Consonant+" },
  { phoneme: "f", grapheme: "gh", graphemeType: "Consonant+" },
  { phoneme: "k", grapheme: "ck", graphemeType: "Consonant+" },
  { phoneme: "kw", grapheme: "qu", graphemeType: "Consonant+" },
  {
    phoneme: "s",
    grapheme: "c",
    graphemeType: "Consonant+",
    tips: "soft c, with i|e|y",
  },
  {
    phoneme: "dʒ",
    grapheme: "g",
    graphemeType: "Consonant+",
    tips: "soft g, with i|e|y",
  },
  { phoneme: "ɑɹ", grapheme: "ar", graphemeType: "Other" },
  { phoneme: "ɝ", grapheme: "ir", graphemeType: "Other" },
  { phoneme: "ɝ", grapheme: "ur", graphemeType: "Other" },
  { phoneme: "ɝ", grapheme: "er", graphemeType: "Other" },
  { phoneme: "ɝ", grapheme: "or", graphemeType: "Other", tips: "end" },
  { phoneme: "ɔɹ", grapheme: "or", graphemeType: "Other", tips: "middle" },
  { phoneme: "ɝ", grapheme: "or", graphemeType: "Other", tips: "after w" },
  { phoneme: "ɔɪ", grapheme: "oi", graphemeType: "Other" },
  { phoneme: "ɔɪ", grapheme: "oy", graphemeType: "Other" },
  { phoneme: "aʊ", grapheme: "ou", graphemeType: "Other" },
  { phoneme: "aʊ", grapheme: "ow", graphemeType: "Other", tips: "?" },
  { phoneme: "ɛɹ", grapheme: "air", graphemeType: "Other" },
  { phoneme: "ɛɹ", grapheme: "are", graphemeType: "Other" },
  { phoneme: "ɛɹ", grapheme: "ear", graphemeType: "Other" },
  { phoneme: "ɪɹ", grapheme: "eer", graphemeType: "Other" },
  { phoneme: "ɪɹ", grapheme: "ear", graphemeType: "Other", tips: "?" },
  { phoneme: "ɪɹ", grapheme: "ere", graphemeType: "Other" },
  { phoneme: "ɔ", grapheme: "au", graphemeType: "Other" },
  { phoneme: "ɔ", grapheme: "aw", graphemeType: "Other" },
  { phoneme: "ɔ", grapheme: "al", graphemeType: "Other" },
  { phoneme: "ɔɫ", grapheme: "all", graphemeType: "Other" },
  { phoneme: "ʊ", grapheme: "oo", graphemeType: "Other", tips: "k" },
  { phoneme: "ʊ", grapheme: "u", graphemeType: "Other", tips: "?" },
  { phoneme: "m", grapheme: "mb", graphemeType: "Other" },
  { phoneme: "n", grapheme: "kn", graphemeType: "Other" },
  { phoneme: "ɹ", grapheme: "wr", graphemeType: "Other" },
  { phoneme: "ʒɝ", grapheme: "sure", graphemeType: "Other" },
  { phoneme: "tʃɝ", grapheme: "ture", graphemeType: "Other" },
  { phoneme: "ʃən", grapheme: "tion", graphemeType: "Other" },
  { phoneme: "ʃən", grapheme: "cian", graphemeType: "Other" },
  { phoneme: "ʃən", grapheme: "sion", graphemeType: "Other" },
  { phoneme: "ʒən", grapheme: "sion", graphemeType: "Other", tips: "?" },
  { phoneme: "əs", grapheme: "ous", graphemeType: "Other" },
  { phoneme: "fəɫ", grapheme: "ful", graphemeType: "Other" },
  { phoneme: "ŋ", grapheme: "ng", graphemeType: "Other" },
  { phoneme: "ŋk", grapheme: "nk", graphemeType: "Other" },
];

export const MAPPINGS = new Map<string, string | string[]>([
  ["b", "b"],
  ["tʃ", "ch"],
  ["d", "d"],
  ["ð", "dh"],
  ["f", "f"],
  ["ɡ", ["g", "gh"]],
  ["h", "h"],
  ["dʒ", "j"],
  ["k", "k"],
  ["x", "kh"],
  ["l", "l"],
  ["m", "m"],
  ["n", "n"],
  ["ŋ", "ng"],
  ["ŋk", "nk"],
  ["p", "p"],
  ["r", "r"],
  ["s", ["s", "ss"]],
  ["ʃ", "sh"],
  ["t", "t"],
  ["tʃ", "tch"],
  ["θ", "th"],
  ["v", "v"],
  ["w", "w"],
  ["hw", "wh"],
  ["j", "y"],
  ["z", "z"],
  ["ʒ", "zh"],
  ["æ", "a"],
  ["ɑː", "ah"],
  ["ɛər", "air"],
  ["ɑːr", "ar"],
  ["ær", "arr"],
  ["ɔː", "aw"],
  ["eɪ", "ay"],
  ["ɛ", ["e", "eh"]],
  ["iː", "ee"],
  ["i", "ee"],
  ["ɪər", "eer"],
  ["ɛr", "err"],
  ["juː", "ew"],
  ["aɪ", ["eye", "y"]],
  ["ɪ", ["i", "ih"]],
  ["aɪər", "ire"],
  ["ɪr", "irr"],
  ["ɒ", "o"],
  ["oʊ", "oh"],
  ["ɔɪər", "oir"],
  ["uː", "oo"],
  ["u", "oo"],
  ["ʊər", "oor"],
  ["ɔːr", "or"],
  ["ɒr", "orr"],
  ["aʊər", "our"],
  ["aʊ", "ow"],
  ["ɔɪ", "oy"],
  ["ʌ", ["u", "uh"]],
  ["ɜːr", "ur"],
  ["jʊər", "ure"],
  ["ʌr", "urr"],
  ["ʊ", "uu"],
  ["ʊr", "uurr"],
  ["ə", "uh"],
  ["ər", "er"],
]);
export const MAP = new Map<string, string>([
  ["i", "iː"],
  ["ɪ", "ɪ"],
  ["e", "eɪ"],
  ["ɛ", "e"],
  ["æ", "æ"],
  ["ɑ", "ɑː"],
  ["o", "əʊ"],
  ["ɔ", "ɔː"],
  ["ɔ", "ɔ"],
  ["u", "uː"],
  ["ᴜ", "ʊ"],
  ["ʌ", "ʌ"],
  ["ə", "ə"],
  ["ɪr", "ɪə"],
  ["ɚ", "ə"],
  ["ɝ", "ɜ"],
  ["aɪ", "aɪ"],
  ["aᴜ", "aʊ"],
  ["ɔɪ", "ɔɪ"],
  ["p", "p"],
  ["t", "t"],
  ["k", "k"],
  ["f", "f"],
  ["s", "s"],
  ["θ", "θ"],
  ["ʃ", "ʃ"],
  ["tʃ", "tʃ"],
  ["h", "h"],
  ["b", "b"],
  ["d", "d"],
  ["g", "g"],
  ["v", "v"],
  ["z", "z"],
  ["ð", "ð"],
  ["ʒ", "ʒ"],
  ["dʒ", "dʒ"],
  ["m", "m"],
  ["n", "n"],
  ["ŋ", "ŋ"],
  ["l", "l"],
  ["r", "r"],
  ["j", "j"],
  ["w", "w"],
]);
