export const LIST = [
  { phoneme: "æ", grapheme: "a", graphemeType: "Alphabet" },
  { phoneme: "b", grapheme: "b", graphemeType: "Alphabet" },
  {
    phoneme: "k",
    grapheme: "c",
    graphemeType: "Alphabet",
    tips: "c 在单词开头",
  },
  { phoneme: "d", grapheme: "d", graphemeType: "Alphabet" },
  { phoneme: "ɛ", grapheme: "e", graphemeType: "Alphabet" },
  { phoneme: "f", grapheme: "f", graphemeType: "Alphabet" },
  { phoneme: "ɡ", grapheme: "g", graphemeType: "Alphabet", tips: "g 一般情况" },
  { phoneme: "h", grapheme: "h", graphemeType: "Alphabet" },
  { phoneme: "ɪ", grapheme: "i", graphemeType: "Alphabet" },
  { phoneme: "dʒ", grapheme: "j", graphemeType: "Alphabet" },
  { phoneme: "k", grapheme: "k", graphemeType: "Alphabet" },
  { phoneme: "ɫ", grapheme: "l", graphemeType: "Alphabet" },
  { phoneme: "m", grapheme: "m", graphemeType: "Alphabet" },
  { phoneme: "n", grapheme: "n", graphemeType: "Alphabet" },
  { phoneme: "ɑ", grapheme: "o", graphemeType: "Alphabet" },
  { phoneme: "p", grapheme: "p", graphemeType: "Alphabet" },
  { phoneme: "kw", grapheme: "q", graphemeType: "Alphabet" },
  { phoneme: "ɹ", grapheme: "r", graphemeType: "Alphabet" },
  { phoneme: "s", grapheme: "s", graphemeType: "Alphabet" },
  { phoneme: "t", grapheme: "t", graphemeType: "Alphabet" },
  {
    phoneme: "ə",
    grapheme: "u",
    graphemeType: "Alphabet",
    tips: "u 在 重读（多个元音时，重读的元音） 闭音节（元音字母被辅音字母关起来）",
  },
  { phoneme: "v", grapheme: "v", graphemeType: "Alphabet" },
  { phoneme: "w", grapheme: "w", graphemeType: "Alphabet" },
  { phoneme: "ks", grapheme: "x", graphemeType: "Alphabet" },
  {
    phoneme: "j",
    grapheme: "y",
    graphemeType: "Alphabet",
    tips: "y 在单词的开头",
  },
  { phoneme: "z", grapheme: "z", graphemeType: "Alphabet" },
  { phoneme: "æd", grapheme: "ad", graphemeType: "ShortVowel+" },
  { phoneme: "æɡ", grapheme: "ag", graphemeType: "ShortVowel+" },
  { phoneme: "æt", grapheme: "at", graphemeType: "ShortVowel+" },
  { phoneme: "æm", grapheme: "am", graphemeType: "ShortVowel+" },
  { phoneme: "æn", grapheme: "an", graphemeType: "ShortVowel+" },
  { phoneme: "æp", grapheme: "ap", graphemeType: "ShortVowel+" },
  { phoneme: "ɛd", grapheme: "ed", graphemeType: "ShortVowel+" },
  { phoneme: "ɛɡ", grapheme: "eg", graphemeType: "ShortVowel+" },
  { phoneme: "ɛn", grapheme: "en", graphemeType: "ShortVowel+" },
  { phoneme: "ɛt", grapheme: "et", graphemeType: "ShortVowel+" },
  { phoneme: "ɛɫ", grapheme: "ell", graphemeType: "ShortVowel+" },
  { phoneme: "ɛs", grapheme: "ess", graphemeType: "ShortVowel+" },
  { phoneme: "ɪɡ", grapheme: "ig", graphemeType: "ShortVowel+" },
  { phoneme: "ɪn", grapheme: "in", graphemeType: "ShortVowel+" },
  { phoneme: "ɪb", grapheme: "ib", graphemeType: "ShortVowel+" },
  { phoneme: "ɪp", grapheme: "ip", graphemeType: "ShortVowel+" },
  { phoneme: "ɪd", grapheme: "id", graphemeType: "ShortVowel+" },
  { phoneme: "ɪt", grapheme: "it", graphemeType: "ShortVowel+" },
  { phoneme: "ɪks", grapheme: "ix", graphemeType: "ShortVowel+" },
  { phoneme: "ɪm", grapheme: "im", graphemeType: "ShortVowel+" },
  { phoneme: "ɪɫ", grapheme: "ill", graphemeType: "ShortVowel+" },
  { phoneme: "ɑp", grapheme: "op", graphemeType: "ShortVowel+" },
  { phoneme: "ɑt", grapheme: "ot", graphemeType: "ShortVowel+" },
  { phoneme: "ɑɡ", grapheme: "og", graphemeType: "ShortVowel+" },
  { phoneme: "ɑks", grapheme: "ox", graphemeType: "ShortVowel+" },
  { phoneme: "ɑd", grapheme: "od", graphemeType: "ShortVowel+" },
  { phoneme: "ɑb", grapheme: "ob", graphemeType: "ShortVowel+" },
  { phoneme: "əb", grapheme: "ub", graphemeType: "ShortVowel+" },
  { phoneme: "əp", grapheme: "up", graphemeType: "ShortVowel+" },
  { phoneme: "əd", grapheme: "ud", graphemeType: "ShortVowel+" },
  { phoneme: "əm", grapheme: "um", graphemeType: "ShortVowel+" },
  { phoneme: "ən", grapheme: "un", graphemeType: "ShortVowel+" },
  { phoneme: "əɫ", grapheme: "ull", graphemeType: "ShortVowel+" },
  { phoneme: "əɡ", grapheme: "ug", graphemeType: "ShortVowel+" },
  { phoneme: "ət", grapheme: "ut", graphemeType: "ShortVowel+" },
  { phoneme: "əs", grapheme: "us", graphemeType: "ShortVowel+" },
  { phoneme: "eɪ", grapheme: "a_e", graphemeType: "LongVowel+" },
  { phoneme: "aɪ", grapheme: "i_e", graphemeType: "LongVowel+" },
  { phoneme: "oʊ", grapheme: "o_e", graphemeType: "LongVowel+" },
  {
    phoneme: "ju",
    grapheme: "u_e",
    graphemeType: "LongVowel+",
    tips: "u_e 一般情况",
  },
  {
    phoneme: "u",
    grapheme: "u_e",
    graphemeType: "LongVowel+",
    tips: "u_e 在 j , l , r , s 这四个字母后",
  },
  { phoneme: "i", grapheme: "e_e", graphemeType: "LongVowel+" },
  { phoneme: "eɪ", grapheme: "ai", graphemeType: "LongVowel+" },
  { phoneme: "eɪ", grapheme: "ay", graphemeType: "LongVowel+" },
  { phoneme: "i", grapheme: "ee", graphemeType: "LongVowel+" },
  { phoneme: "i", grapheme: "ea", graphemeType: "LongVowel+" },
  { phoneme: "i", grapheme: "ey", graphemeType: "LongVowel+" },
  {
    phoneme: "i",
    grapheme: "y",
    graphemeType: "LongVowel+",
    tips: "y 在多音节（两个元音+）单词的结尾",
  },
  { phoneme: "aɪ", grapheme: "ie", graphemeType: "LongVowel+" },
  { phoneme: "aɪ", grapheme: "igh", graphemeType: "LongVowel+" },
  {
    phoneme: "aɪ",
    grapheme: "y",
    graphemeType: "LongVowel+",
    tips: "y 在单音节（一个元音）单词的结尾",
  },
  { phoneme: "oʊ", grapheme: "oa", graphemeType: "LongVowel+" },
  {
    phoneme: "oʊ",
    grapheme: "ow",
    graphemeType: "LongVowel+",
    tips: "ow 在单词结尾",
  },
  { phoneme: "ju", grapheme: "ew", graphemeType: "LongVowel+" },
  {
    phoneme: "ju",
    grapheme: "ue",
    graphemeType: "LongVowel+",
    tips: "ue 一船情况",
  },
  {
    phoneme: "u",
    grapheme: "ue",
    graphemeType: "LongVowel+",
    tips: "ue 遇到字母 s , l",
  },
  { phoneme: "u", grapheme: "ui", graphemeType: "LongVowel+" },
  {
    phoneme: "u",
    grapheme: "oo",
    graphemeType: "LongVowel+",
    tips: "oo 一般情况",
  },
  { phoneme: "bɫ", grapheme: "bl", graphemeType: "Consonant+" },
  { phoneme: "pɫ", grapheme: "pl", graphemeType: "Consonant+" },
  { phoneme: "kɫ", grapheme: "cl", graphemeType: "Consonant+" },
  { phoneme: "fɫ", grapheme: "fl", graphemeType: "Consonant+" },
  { phoneme: "ɡɫ", grapheme: "gl", graphemeType: "Consonant+" },
  { phoneme: "sɫ", grapheme: "sl", graphemeType: "Consonant+" },
  { phoneme: "pɹ", grapheme: "pr", graphemeType: "Consonant+" },
  { phoneme: "bɹ", grapheme: "br", graphemeType: "Consonant+" },
  { phoneme: "kɹ", grapheme: "cr", graphemeType: "Consonant+" },
  { phoneme: "ɡɹ", grapheme: "gr", graphemeType: "Consonant+" },
  { phoneme: "fɹ", grapheme: "fr", graphemeType: "Consonant+" },
  { phoneme: "tɹ", grapheme: "tr", graphemeType: "Consonant+" },
  { phoneme: "dɹ", grapheme: "dr", graphemeType: "Consonant+" },
  { phoneme: "sm", grapheme: "sm", graphemeType: "Consonant+" },
  { phoneme: "sn", grapheme: "sn", graphemeType: "Consonant+" },
  { phoneme: "sw", grapheme: "sw", graphemeType: "Consonant+" },
  { phoneme: "stɹ", grapheme: "str", graphemeType: "Consonant+" },
  { phoneme: "sp", grapheme: "sp", graphemeType: "Consonant+" },
  { phoneme: "st", grapheme: "st", graphemeType: "Consonant+" },
  { phoneme: "sk", grapheme: "sk", graphemeType: "Consonant+" },
  { phoneme: "sk", grapheme: "sc", graphemeType: "Consonant+" },
  { phoneme: "ʃ", grapheme: "sh", graphemeType: "Consonant+" },
  { phoneme: "f", grapheme: "ph", graphemeType: "Consonant+" },
  {
    phoneme: "θ",
    grapheme: "th",
    graphemeType: "Consonant+",
    tips: "th 在单词开头和结尾时",
  },
  {
    phoneme: "ð",
    grapheme: "th",
    graphemeType: "Consonant+",
    tips: "th 在 代、介、连、副、冠 词时；在单词中间时",
  },
  { phoneme: "w", grapheme: "wh", graphemeType: "Consonant+" },
  { phoneme: "tʃ", grapheme: "ch", graphemeType: "Consonant+" },
  { phoneme: "tʃ", grapheme: "tch", graphemeType: "Consonant+" },
  { phoneme: "f", grapheme: "gh", graphemeType: "Consonant+" },
  { phoneme: "k", grapheme: "ck", graphemeType: "Consonant+" },
  { phoneme: "kw", grapheme: "qu", graphemeType: "Consonant+" },
  {
    phoneme: "s",
    grapheme: "c",
    graphemeType: "Consonant+",
    tips: "c 遇到字母 i , e , y",
  },
  {
    phoneme: "dʒ",
    grapheme: "g",
    graphemeType: "Consonant+",
    tips: "g 遇到字母 i , e , y",
  },
  { phoneme: "ɑɹ", grapheme: "ar", graphemeType: "Other" },
  { phoneme: "ɝ", grapheme: "ir", graphemeType: "Other" },
  { phoneme: "ɝ", grapheme: "ur", graphemeType: "Other" },
  { phoneme: "ɝ", grapheme: "er", graphemeType: "Other" },
  {
    phoneme: "ɝ",
    grapheme: "or",
    graphemeType: "Other",
    tips: "or 在单词结尾",
  },
  {
    phoneme: "ɔɹ",
    grapheme: "or",
    graphemeType: "Other",
    tips: "or 在单词中间",
  },
  {
    phoneme: "ɝ",
    grapheme: "or",
    graphemeType: "Other",
    tips: "or 在字母 w 后面",
  },
  { phoneme: "ɔɪ", grapheme: "oi", graphemeType: "Other" },
  { phoneme: "ɔɪ", grapheme: "oy", graphemeType: "Other" },
  { phoneme: "aʊ", grapheme: "ou", graphemeType: "Other" },
  {
    phoneme: "aʊ",
    grapheme: "ow",
    graphemeType: "Other",
    tips: "ow 在单词中间",
  },
  { phoneme: "ɛɹ", grapheme: "air", graphemeType: "Other" },
  { phoneme: "ɛɹ", grapheme: "are", graphemeType: "Other" },
  {
    phoneme: "ɛɹ",
    grapheme: "ear",
    graphemeType: "Other",
    tips: "ear 在字母 b , p , w 后",
  },
  { phoneme: "ɪɹ", grapheme: "eer", graphemeType: "Other" },
  {
    phoneme: "ɪɹ",
    grapheme: "ear",
    graphemeType: "Other",
    tips: "ear 在单词结尾",
  },
  { phoneme: "ɪɹ", grapheme: "ere", graphemeType: "Other" },
  { phoneme: "ɔ", grapheme: "au", graphemeType: "Other" },
  { phoneme: "ɔ", grapheme: "aw", graphemeType: "Other" },
  { phoneme: "ɔ", grapheme: "al", graphemeType: "Other" },
  { phoneme: "ɔɫ", grapheme: "all", graphemeType: "Other" },
  {
    phoneme: "ʊ",
    grapheme: "oo",
    graphemeType: "Other",
    tips: "oo 在字母 k 前时；好、脚、站在、羊毛、木头 时",
  },
  {
    phoneme: "ʊ",
    grapheme: "u",
    graphemeType: "Other",
    tips: "u 在 推、拉、放、满 时",
  },
  { phoneme: "m", grapheme: "mb", graphemeType: "Other" },
  { phoneme: "n", grapheme: "kn", graphemeType: "Other" },
  { phoneme: "ɹ", grapheme: "wr", graphemeType: "Other" },
  { phoneme: "ʒɝ", grapheme: "sure", graphemeType: "Other" },
  { phoneme: "tʃɝ", grapheme: "ture", graphemeType: "Other" },
  { phoneme: "ʃən", grapheme: "tion", graphemeType: "Other" },
  { phoneme: "ʃən", grapheme: "cian", graphemeType: "Other" },
  {
    phoneme: "ʃən",
    grapheme: "sion",
    graphemeType: "Other",
    tips: "sion 遇到辅音",
  },
  {
    phoneme: "ʒən",
    grapheme: "sion",
    graphemeType: "Other",
    tips: "sion 遇到元音",
  },
  { phoneme: "əs", grapheme: "ous", graphemeType: "Other" },
  { phoneme: "fəɫ", grapheme: "ful", graphemeType: "Other" },
  { phoneme: "ŋ", grapheme: "ng", graphemeType: "Other" },
  { phoneme: "ŋk", grapheme: "nk", graphemeType: "Other" },
];

export const POS = [
  "prep.&conj.",
  "adj.&pron.",
  "vt.&vi.",
  "vi.&vt.",
  "pron.",
  "conj.",
  "prep.",
  "abbr.",
  "det.",
  "adv.",
  "aux.",
  "adj.",
  "int.",
  "num.",
  "art.",
  "vt.",
  "vi.",
  "na.",
  "n.",
  "v.",
];
